---
driver:
  name: vagrant
  provider: parallels

provisioner:
  product_name: chef
  product_version: latest
  always_update_cookbooks: true
  multiple_converge: 2
  enforce_idempotency: true
  data_bags_path: ./test/fixtures/data_bags

verifier:
  name: inspec
  reporter:
    - cli
    - junit:/tmp/junit.xml
  inspec_tests:
    - test/integration/default

platforms:
- name: ubuntu-16.04
  driver:
    name: azurerm
    image_urn: Canonical:UbuntuServer:16.04-LTS:latest
    location: <%= ENV['AZURE_LOCATION'] %>
    machine_size: 'Standard_D3_v2'
    subscription_id: <%= ENV['AZURE_SUBSCRIPTION_ID'] %>
    vnet_id: /subscriptions/<%= ENV['AZURE_SUBSCRIPTION_ID'] %>/resourceGroups/<%= ENV['AZURE_ER_RESOURCE_GROUP'] %>/providers/Microsoft.Network/virtualNetworks/<%= ENV['AZURE_ER_VNET_NAME'] %>
    subnet_id: Subnet-1

- name: macos-10.13
- name: macos-10.14

suites:
- name: default
  run_list:
    - recipe[snipeit_api_test::configure_snipeit]
  includes:
    - ubuntu-16.04
  attributes:
    snipeit:
      api:
        instance: <%= ENV['SNIPEIT_URL'] %>
